// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/api/annotations/versioning.proto

package udpa_api_annotations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VersioningAnnotation struct {
	PreviousMessageType  string   `protobuf:"bytes,1,opt,name=previous_message_type,json=previousMessageType,proto3" json:"previous_message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersioningAnnotation) Reset()         { *m = VersioningAnnotation{} }
func (m *VersioningAnnotation) String() string { return proto.CompactTextString(m) }
func (*VersioningAnnotation) ProtoMessage()    {}
func (*VersioningAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd1940c3210a279, []int{0}
}

func (m *VersioningAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersioningAnnotation.Unmarshal(m, b)
}
func (m *VersioningAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersioningAnnotation.Marshal(b, m, deterministic)
}
func (m *VersioningAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersioningAnnotation.Merge(m, src)
}
func (m *VersioningAnnotation) XXX_Size() int {
	return xxx_messageInfo_VersioningAnnotation.Size(m)
}
func (m *VersioningAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_VersioningAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_VersioningAnnotation proto.InternalMessageInfo

func (m *VersioningAnnotation) GetPreviousMessageType() string {
	if m != nil {
		return m.PreviousMessageType
	}
	return ""
}

var E_Versioning = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*VersioningAnnotation)(nil),
	Field:         7881811,
	Name:          "udpa.api.annotations.versioning",
	Tag:           "bytes,7881811,opt,name=versioning",
	Filename:      "udpa/api/annotations/versioning.proto",
}

func init() {
	proto.RegisterType((*VersioningAnnotation)(nil), "udpa.api.annotations.VersioningAnnotation")
	proto.RegisterExtension(E_Versioning)
}

func init() {
	proto.RegisterFile("udpa/api/annotations/versioning.proto", fileDescriptor_0fd1940c3210a279)
}

var fileDescriptor_0fd1940c3210a279 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x4d, 0x29, 0x48,
	0xd4, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b,
	0xd6, 0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0xcb, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x12, 0x01, 0x29, 0xd3, 0x4b, 0x2c, 0xc8, 0xd4, 0x43, 0x52, 0x26, 0xa5, 0x90, 0x9e,
	0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x0f, 0x56, 0x93, 0x54, 0x9a, 0xa6, 0x9f, 0x92, 0x5a, 0x9c, 0x5c,
	0x94, 0x59, 0x50, 0x92, 0x5f, 0x04, 0xd1, 0xa7, 0xe4, 0xc5, 0x25, 0x12, 0x06, 0x37, 0xcb, 0x11,
	0xae, 0x55, 0xc8, 0x88, 0x4b, 0xb4, 0xa0, 0x28, 0xb5, 0x2c, 0x33, 0xbf, 0xb4, 0x38, 0x3e, 0x37,
	0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x35, 0xbe, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x48, 0x18, 0x26, 0xe9, 0x0b, 0x91, 0x0b, 0xa9, 0x2c, 0x48, 0xb5, 0xca, 0xe3, 0xe2, 0x42,
	0xb8, 0x4b, 0x48, 0x5e, 0x0f, 0x62, 0xb9, 0x1e, 0xcc, 0x72, 0x3d, 0xa8, 0x5a, 0xff, 0x02, 0xb0,
	0xe3, 0x24, 0x2e, 0x77, 0x3c, 0x64, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0xd2, 0xd2, 0xc3, 0xe6, 0x78,
	0x3d, 0x6c, 0xee, 0x0a, 0x42, 0xb2, 0x21, 0x89, 0x0d, 0x6c, 0xb2, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xb7, 0x92, 0x7c, 0xba, 0x23, 0x01, 0x00, 0x00,
}
