load("//bazel:api_build_system.bzl", "udpa_proto_library", "udpa_proto_package")

licenses(["notice"])  # Apache 2

udpa_proto_library(
    name = "typed_struct",
    srcs = ["typed_struct.proto"],
    visibility = ["//visibility:public"],
)

udpa_proto_package()
