// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/core/v1/collection_resource.proto

package udpa_core_v1

import (
	fmt "fmt"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CollectionResource struct {
	// Types that are valid to be assigned to ResourceSpecifier:
	//	*CollectionResource_Locator
	//	*CollectionResource_Entry
	ResourceSpecifier    isCollectionResource_ResourceSpecifier `protobuf_oneof:"resource_specifier"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *CollectionResource) Reset()         { *m = CollectionResource{} }
func (m *CollectionResource) String() string { return proto.CompactTextString(m) }
func (*CollectionResource) ProtoMessage()    {}
func (*CollectionResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_a105f4a9571f0c96, []int{0}
}

func (m *CollectionResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionResource.Unmarshal(m, b)
}
func (m *CollectionResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionResource.Marshal(b, m, deterministic)
}
func (m *CollectionResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionResource.Merge(m, src)
}
func (m *CollectionResource) XXX_Size() int {
	return xxx_messageInfo_CollectionResource.Size(m)
}
func (m *CollectionResource) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionResource.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionResource proto.InternalMessageInfo

type isCollectionResource_ResourceSpecifier interface {
	isCollectionResource_ResourceSpecifier()
}

type CollectionResource_Locator struct {
	Locator *ResourceLocator `protobuf:"bytes,1,opt,name=locator,proto3,oneof"`
}

type CollectionResource_Entry struct {
	Entry *CollectionResource_InlineEntry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"`
}

func (*CollectionResource_Locator) isCollectionResource_ResourceSpecifier() {}

func (*CollectionResource_Entry) isCollectionResource_ResourceSpecifier() {}

func (m *CollectionResource) GetResourceSpecifier() isCollectionResource_ResourceSpecifier {
	if m != nil {
		return m.ResourceSpecifier
	}
	return nil
}

func (m *CollectionResource) GetLocator() *ResourceLocator {
	if x, ok := m.GetResourceSpecifier().(*CollectionResource_Locator); ok {
		return x.Locator
	}
	return nil
}

func (m *CollectionResource) GetEntry() *CollectionResource_InlineEntry {
	if x, ok := m.GetResourceSpecifier().(*CollectionResource_Entry); ok {
		return x.Entry
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CollectionResource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CollectionResource_Locator)(nil),
		(*CollectionResource_Entry)(nil),
	}
}

type CollectionResource_InlineEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Resource             *any.Any `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionResource_InlineEntry) Reset()         { *m = CollectionResource_InlineEntry{} }
func (m *CollectionResource_InlineEntry) String() string { return proto.CompactTextString(m) }
func (*CollectionResource_InlineEntry) ProtoMessage()    {}
func (*CollectionResource_InlineEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a105f4a9571f0c96, []int{0, 0}
}

func (m *CollectionResource_InlineEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionResource_InlineEntry.Unmarshal(m, b)
}
func (m *CollectionResource_InlineEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionResource_InlineEntry.Marshal(b, m, deterministic)
}
func (m *CollectionResource_InlineEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionResource_InlineEntry.Merge(m, src)
}
func (m *CollectionResource_InlineEntry) XXX_Size() int {
	return xxx_messageInfo_CollectionResource_InlineEntry.Size(m)
}
func (m *CollectionResource_InlineEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionResource_InlineEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionResource_InlineEntry proto.InternalMessageInfo

func (m *CollectionResource_InlineEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollectionResource_InlineEntry) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CollectionResource_InlineEntry) GetResource() *any.Any {
	if m != nil {
		return m.Resource
	}
	return nil
}

func init() {
	proto.RegisterType((*CollectionResource)(nil), "udpa.core.v1.CollectionResource")
	proto.RegisterType((*CollectionResource_InlineEntry)(nil), "udpa.core.v1.CollectionResource.InlineEntry")
}

func init() {
	proto.RegisterFile("udpa/core/v1/collection_resource.proto", fileDescriptor_a105f4a9571f0c96)
}

var fileDescriptor_a105f4a9571f0c96 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4f, 0x2a, 0x31,
	0x14, 0xc5, 0x19, 0x78, 0x8f, 0x3f, 0xe5, 0xad, 0x9a, 0x67, 0x18, 0x08, 0x24, 0x46, 0x8d, 0x31,
	0xd1, 0xe9, 0x00, 0xae, 0x70, 0xc7, 0xa8, 0x09, 0x26, 0x2e, 0xc8, 0x2c, 0x15, 0x25, 0xa5, 0x14,
	0x6c, 0x32, 0xb4, 0xa4, 0xd3, 0x99, 0x04, 0x17, 0xc6, 0xbd, 0xdf, 0xc8, 0x85, 0x6b, 0xb7, 0x7e,
	0x1b, 0xe3, 0xca, 0x4c, 0x67, 0x4a, 0x20, 0xec, 0xda, 0xdc, 0xdf, 0xb9, 0xe7, 0xdc, 0x03, 0x8e,
	0xa3, 0xe9, 0x12, 0xbb, 0x44, 0x48, 0xea, 0xc6, 0x1d, 0x97, 0x88, 0x20, 0xa0, 0x44, 0x31, 0xc1,
	0xc7, 0x92, 0x86, 0x22, 0x92, 0x84, 0xa2, 0xa5, 0x14, 0x4a, 0xc0, 0x7f, 0x09, 0x87, 0x12, 0x0e,
	0xc5, 0x9d, 0x46, 0x7d, 0x2e, 0xc4, 0x3c, 0xa0, 0xae, 0x9e, 0x4d, 0xa2, 0x99, 0x8b, 0xf9, 0x2a,
	0x05, 0x1b, 0x2d, 0xbd, 0x10, 0x73, 0x2e, 0x14, 0x4e, 0x16, 0x85, 0x6e, 0xa8, 0xb0, 0x8a, 0xc2,
	0x6c, 0x7c, 0xb8, 0xe5, 0x67, 0x4c, 0xc6, 0x81, 0x20, 0x58, 0x09, 0x99, 0x41, 0xb5, 0x18, 0x07,
	0x6c, 0x8a, 0x15, 0x75, 0xcd, 0x23, 0x1d, 0x1c, 0x7c, 0xe4, 0x01, 0xbc, 0x5c, 0x67, 0xf4, 0x33,
	0x35, 0xec, 0x81, 0x52, 0xb6, 0xc0, 0xb6, 0xf6, 0xad, 0x93, 0x6a, 0xb7, 0x85, 0x36, 0xe3, 0x22,
	0x03, 0xde, 0xa6, 0xd0, 0x20, 0xe7, 0x1b, 0x1e, 0x5e, 0x81, 0xbf, 0x94, 0x2b, 0xb9, 0xb2, 0xf3,
	0x5a, 0x78, 0xb6, 0x2d, 0xdc, 0xf5, 0x42, 0x37, 0x3c, 0x60, 0x9c, 0x5e, 0x27, 0x9a, 0x41, 0xce,
	0x4f, 0xc5, 0x8d, 0x37, 0x0b, 0x54, 0x37, 0x06, 0xb0, 0x0d, 0xfe, 0x70, 0xbc, 0xa0, 0x3a, 0x4d,
	0xc5, 0x6b, 0xfe, 0x78, 0x75, 0x59, 0xeb, 0xee, 0x3d, 0xde, 0xb7, 0x9d, 0x1e, 0x76, 0x9e, 0xfb,
	0xce, 0xdd, 0x78, 0xe4, 0x8c, 0xd0, 0xcb, 0xc5, 0xc3, 0xe9, 0x91, 0xaf, 0x49, 0x68, 0x83, 0x52,
	0x4c, 0x65, 0xc8, 0x04, 0xd7, 0x49, 0x2a, 0xbe, 0xf9, 0xc2, 0x36, 0x28, 0x9b, 0x9a, 0xec, 0x82,
	0x0e, 0xf9, 0x1f, 0xa5, 0xf5, 0x23, 0x53, 0x3f, 0xea, 0xf3, 0x95, 0xbf, 0xa6, 0xbc, 0x3a, 0x80,
	0xeb, 0x62, 0xc3, 0x25, 0x25, 0x6c, 0xc6, 0xa8, 0x84, 0x85, 0x6f, 0xcf, 0xf2, 0xfa, 0xef, 0xaf,
	0x9f, 0x5f, 0xc5, 0x7c, 0xd9, 0x02, 0x4d, 0x22, 0x16, 0x68, 0xce, 0xd4, 0x53, 0x34, 0x49, 0x6f,
	0xde, 0x3c, 0xdc, 0xab, 0xed, 0x5e, 0x3e, 0x4c, 0xcc, 0x86, 0xd6, 0xa4, 0xa8, 0x5d, 0xcf, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xab, 0x78, 0x80, 0x3a, 0x02, 0x00, 0x00,
}
