// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: udpa/core/v1/collection_resource.proto

package udpa_core_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _collection_resource_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on CollectionResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CollectionResource) Validate() error {
	if m == nil {
		return nil
	}

	switch m.ResourceSpecifier.(type) {

	case *CollectionResource_Locator:

		if v, ok := interface{}(m.GetLocator()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CollectionResourceValidationError{
					field:  "Locator",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *CollectionResource_Entry:

		if v, ok := interface{}(m.GetEntry()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CollectionResourceValidationError{
					field:  "Entry",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		return CollectionResourceValidationError{
			field:  "ResourceSpecifier",
			reason: "value is required",
		}

	}

	return nil
}

// CollectionResourceValidationError is the validation error returned by
// CollectionResource.Validate if the designated constraints aren't met.
type CollectionResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CollectionResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CollectionResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CollectionResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CollectionResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CollectionResourceValidationError) ErrorName() string {
	return "CollectionResourceValidationError"
}

// Error satisfies the builtin error interface
func (e CollectionResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCollectionResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CollectionResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CollectionResourceValidationError{}

// Validate checks the field values on CollectionResource_InlineEntry with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CollectionResource_InlineEntry) Validate() error {
	if m == nil {
		return nil
	}

	if !_CollectionResource_InlineEntry_Name_Pattern.MatchString(m.GetName()) {
		return CollectionResource_InlineEntryValidationError{
			field:  "Name",
			reason: "value does not match regex pattern \"^[0-9a-zA-Z_\\\\-\\\\.~:]+$\"",
		}
	}

	// no validation rules for Version

	if v, ok := interface{}(m.GetResource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CollectionResource_InlineEntryValidationError{
				field:  "Resource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CollectionResource_InlineEntryValidationError is the validation error
// returned by CollectionResource_InlineEntry.Validate if the designated
// constraints aren't met.
type CollectionResource_InlineEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CollectionResource_InlineEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CollectionResource_InlineEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CollectionResource_InlineEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CollectionResource_InlineEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CollectionResource_InlineEntryValidationError) ErrorName() string {
	return "CollectionResource_InlineEntryValidationError"
}

// Error satisfies the builtin error interface
func (e CollectionResource_InlineEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCollectionResource_InlineEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CollectionResource_InlineEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CollectionResource_InlineEntryValidationError{}

var _CollectionResource_InlineEntry_Name_Pattern = regexp.MustCompile("^[0-9a-zA-Z_\\-\\.~:]+$")
