// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/core/v1/resource_locator.proto

package udpa_core_v1

import (
	fmt "fmt"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceLocator_Scheme int32

const (
	ResourceLocator_UDPA ResourceLocator_Scheme = 0
	ResourceLocator_HTTP ResourceLocator_Scheme = 1
	ResourceLocator_FILE ResourceLocator_Scheme = 2
)

var ResourceLocator_Scheme_name = map[int32]string{
	0: "UDPA",
	1: "HTTP",
	2: "FILE",
}

var ResourceLocator_Scheme_value = map[string]int32{
	"UDPA": 0,
	"HTTP": 1,
	"FILE": 2,
}

func (x ResourceLocator_Scheme) String() string {
	return proto.EnumName(ResourceLocator_Scheme_name, int32(x))
}

func (ResourceLocator_Scheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b10c84cf310f3232, []int{0, 0}
}

type ResourceLocator struct {
	Scheme       ResourceLocator_Scheme `protobuf:"varint,1,opt,name=scheme,proto3,enum=udpa.core.v1.ResourceLocator_Scheme" json:"scheme,omitempty"`
	Id           string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Authority    string                 `protobuf:"bytes,3,opt,name=authority,proto3" json:"authority,omitempty"`
	ResourceType string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// Types that are valid to be assigned to ContextParamSpecifier:
	//	*ResourceLocator_ExactContext
	ContextParamSpecifier isResourceLocator_ContextParamSpecifier `protobuf_oneof:"context_param_specifier"`
	Directives            []*ResourceLocator_Directive            `protobuf:"bytes,6,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                                `json:"-"`
	XXX_unrecognized      []byte                                  `json:"-"`
	XXX_sizecache         int32                                   `json:"-"`
}

func (m *ResourceLocator) Reset()         { *m = ResourceLocator{} }
func (m *ResourceLocator) String() string { return proto.CompactTextString(m) }
func (*ResourceLocator) ProtoMessage()    {}
func (*ResourceLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_b10c84cf310f3232, []int{0}
}

func (m *ResourceLocator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceLocator.Unmarshal(m, b)
}
func (m *ResourceLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceLocator.Marshal(b, m, deterministic)
}
func (m *ResourceLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceLocator.Merge(m, src)
}
func (m *ResourceLocator) XXX_Size() int {
	return xxx_messageInfo_ResourceLocator.Size(m)
}
func (m *ResourceLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceLocator.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceLocator proto.InternalMessageInfo

func (m *ResourceLocator) GetScheme() ResourceLocator_Scheme {
	if m != nil {
		return m.Scheme
	}
	return ResourceLocator_UDPA
}

func (m *ResourceLocator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResourceLocator) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *ResourceLocator) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

type isResourceLocator_ContextParamSpecifier interface {
	isResourceLocator_ContextParamSpecifier()
}

type ResourceLocator_ExactContext struct {
	ExactContext *ContextParams `protobuf:"bytes,5,opt,name=exact_context,json=exactContext,proto3,oneof"`
}

func (*ResourceLocator_ExactContext) isResourceLocator_ContextParamSpecifier() {}

func (m *ResourceLocator) GetContextParamSpecifier() isResourceLocator_ContextParamSpecifier {
	if m != nil {
		return m.ContextParamSpecifier
	}
	return nil
}

func (m *ResourceLocator) GetExactContext() *ContextParams {
	if x, ok := m.GetContextParamSpecifier().(*ResourceLocator_ExactContext); ok {
		return x.ExactContext
	}
	return nil
}

func (m *ResourceLocator) GetDirectives() []*ResourceLocator_Directive {
	if m != nil {
		return m.Directives
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ResourceLocator) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ResourceLocator_ExactContext)(nil),
	}
}

type ResourceLocator_Directive struct {
	// Types that are valid to be assigned to Directive:
	//	*ResourceLocator_Directive_Alt
	//	*ResourceLocator_Directive_Entry
	Directive            isResourceLocator_Directive_Directive `protobuf_oneof:"directive"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ResourceLocator_Directive) Reset()         { *m = ResourceLocator_Directive{} }
func (m *ResourceLocator_Directive) String() string { return proto.CompactTextString(m) }
func (*ResourceLocator_Directive) ProtoMessage()    {}
func (*ResourceLocator_Directive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b10c84cf310f3232, []int{0, 0}
}

func (m *ResourceLocator_Directive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceLocator_Directive.Unmarshal(m, b)
}
func (m *ResourceLocator_Directive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceLocator_Directive.Marshal(b, m, deterministic)
}
func (m *ResourceLocator_Directive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceLocator_Directive.Merge(m, src)
}
func (m *ResourceLocator_Directive) XXX_Size() int {
	return xxx_messageInfo_ResourceLocator_Directive.Size(m)
}
func (m *ResourceLocator_Directive) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceLocator_Directive.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceLocator_Directive proto.InternalMessageInfo

type isResourceLocator_Directive_Directive interface {
	isResourceLocator_Directive_Directive()
}

type ResourceLocator_Directive_Alt struct {
	Alt *ResourceLocator `protobuf:"bytes,1,opt,name=alt,proto3,oneof"`
}

type ResourceLocator_Directive_Entry struct {
	Entry string `protobuf:"bytes,2,opt,name=entry,proto3,oneof"`
}

func (*ResourceLocator_Directive_Alt) isResourceLocator_Directive_Directive() {}

func (*ResourceLocator_Directive_Entry) isResourceLocator_Directive_Directive() {}

func (m *ResourceLocator_Directive) GetDirective() isResourceLocator_Directive_Directive {
	if m != nil {
		return m.Directive
	}
	return nil
}

func (m *ResourceLocator_Directive) GetAlt() *ResourceLocator {
	if x, ok := m.GetDirective().(*ResourceLocator_Directive_Alt); ok {
		return x.Alt
	}
	return nil
}

func (m *ResourceLocator_Directive) GetEntry() string {
	if x, ok := m.GetDirective().(*ResourceLocator_Directive_Entry); ok {
		return x.Entry
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ResourceLocator_Directive) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ResourceLocator_Directive_Alt)(nil),
		(*ResourceLocator_Directive_Entry)(nil),
	}
}

func init() {
	proto.RegisterEnum("udpa.core.v1.ResourceLocator_Scheme", ResourceLocator_Scheme_name, ResourceLocator_Scheme_value)
	proto.RegisterType((*ResourceLocator)(nil), "udpa.core.v1.ResourceLocator")
	proto.RegisterType((*ResourceLocator_Directive)(nil), "udpa.core.v1.ResourceLocator.Directive")
}

func init() {
	proto.RegisterFile("udpa/core/v1/resource_locator.proto", fileDescriptor_b10c84cf310f3232)
}

var fileDescriptor_b10c84cf310f3232 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0x99, 0x02, 0x15, 0x06, 0x76, 0x6d, 0x26, 0xc6, 0xad, 0xc8, 0x46, 0x5c, 0x37, 0x4a,
	0xa2, 0xb4, 0x52, 0x0f, 0x46, 0x0f, 0x26, 0x3b, 0xae, 0x2b, 0x26, 0x7b, 0x68, 0x2a, 0x5e, 0x74,
	0xb5, 0x99, 0x6d, 0x47, 0x99, 0x04, 0x3a, 0xcd, 0xf4, 0x95, 0x2c, 0x1e, 0x8c, 0xf1, 0xe6, 0xd1,
	0xaf, 0xe3, 0x27, 0xf0, 0xea, 0xb7, 0x31, 0x9c, 0x4c, 0x5b, 0x60, 0x61, 0x0f, 0xdc, 0x26, 0xef,
	0xfd, 0xde, 0xcb, 0xff, 0xff, 0x9f, 0x87, 0xef, 0xa5, 0x61, 0xcc, 0xec, 0x40, 0x2a, 0x6e, 0x4f,
	0xfb, 0xb6, 0xe2, 0x89, 0x4c, 0x55, 0xc0, 0xfd, 0xb1, 0x0c, 0x18, 0x48, 0x65, 0xc5, 0x4a, 0x82,
	0x24, 0xcd, 0x0c, 0xb2, 0x32, 0xc8, 0x9a, 0xf6, 0x5b, 0xfb, 0xf9, 0x08, 0x8b, 0x22, 0x09, 0x0c,
	0x84, 0x8c, 0x12, 0x3b, 0x01, 0x06, 0x69, 0x52, 0xc0, 0xad, 0xbb, 0x1b, 0x1b, 0x03, 0x19, 0x01,
	0xbf, 0x00, 0x3f, 0x66, 0x8a, 0x4d, 0x96, 0xc8, 0xde, 0x94, 0x8d, 0x45, 0xc8, 0x80, 0xdb, 0xcb,
	0x47, 0xd1, 0x38, 0xf8, 0x55, 0xc1, 0xd7, 0xbd, 0x85, 0x86, 0xd3, 0x42, 0x02, 0x39, 0xc1, 0x7a,
	0x12, 0x8c, 0xf8, 0x84, 0x9b, 0xa8, 0x83, 0xba, 0xbb, 0xce, 0xa1, 0xb5, 0xae, 0xc6, 0xba, 0x82,
	0x5b, 0x6f, 0x73, 0x96, 0xd6, 0xe6, 0xb4, 0xfa, 0x03, 0x69, 0x06, 0xf2, 0x16, 0xd3, 0x64, 0x17,
	0x6b, 0x22, 0x34, 0xb5, 0x0e, 0xea, 0xd6, 0x3d, 0x4d, 0x84, 0xa4, 0x8d, 0xeb, 0x2c, 0x85, 0x91,
	0x54, 0x02, 0x66, 0x66, 0x39, 0x2f, 0x5f, 0x16, 0xc8, 0x23, 0xbc, 0xb3, 0x0a, 0x03, 0x66, 0x31,
	0x37, 0x2b, 0x19, 0x41, 0xaf, 0xcd, 0x69, 0x45, 0x65, 0x5b, 0x9b, 0xcb, 0xee, 0x70, 0x16, 0x73,
	0x42, 0xf1, 0x0e, 0xbf, 0x60, 0x01, 0xf8, 0x0b, 0xbb, 0x66, 0xb5, 0x83, 0xba, 0x0d, 0xe7, 0xf6,
	0xa6, 0xd4, 0x97, 0x45, 0xd3, 0xcd, 0xa3, 0x18, 0x94, 0xbc, 0x66, 0x3e, 0xb3, 0xa8, 0x92, 0xd7,
	0x18, 0x87, 0x42, 0xf1, 0x00, 0xc4, 0x94, 0x27, 0xa6, 0xde, 0x29, 0x77, 0x1b, 0xce, 0x83, 0xed,
	0x5e, 0x8f, 0x97, 0xbc, 0xb7, 0x36, 0xda, 0xfa, 0x89, 0x70, 0x7d, 0xd5, 0x21, 0x7d, 0x5c, 0x66,
	0x63, 0xc8, 0xb3, 0x6b, 0x38, 0xfb, 0x5b, 0xf7, 0x0d, 0x4a, 0x5e, 0xc6, 0x92, 0xa7, 0xb8, 0xca,
	0x23, 0x50, 0xb3, 0x22, 0x2c, 0x7a, 0x67, 0x4e, 0xdb, 0xaa, 0x65, 0x20, 0xe7, 0xe6, 0xa7, 0x0f,
	0x8f, 0x7b, 0xcf, 0x58, 0xef, 0xeb, 0x51, 0xef, 0xbd, 0x7f, 0xd6, 0x3b, 0xb3, 0xec, 0x6f, 0xcf,
	0x3f, 0x3e, 0x3c, 0x1c, 0x94, 0xbc, 0x82, 0xa7, 0x06, 0xae, 0xaf, 0x74, 0x90, 0xf2, 0x3f, 0x8a,
	0x0e, 0xee, 0x63, 0xbd, 0xf8, 0x10, 0x52, 0xc3, 0x95, 0x77, 0xc7, 0xee, 0x91, 0x51, 0xca, 0x5e,
	0x83, 0xe1, 0xd0, 0x35, 0x50, 0xf6, 0x3a, 0x79, 0x73, 0xfa, 0xca, 0xd0, 0xe8, 0x2d, 0xbc, 0xb7,
	0x71, 0x29, 0x7e, 0x12, 0xf3, 0x40, 0x7c, 0x16, 0x5c, 0xd1, 0x17, 0xbf, 0xbf, 0xff, 0xf9, 0xab,
	0x6b, 0x35, 0x84, 0xdb, 0x81, 0x9c, 0x58, 0x5f, 0x04, 0x8c, 0xd2, 0xf3, 0xc2, 0xc7, 0xba, 0x19,
	0x7a, 0xe3, 0x8a, 0x1b, 0x37, 0xbb, 0x28, 0x17, 0x9d, 0xeb, 0xf9, 0x69, 0x3d, 0xf9, 0x1f, 0x00,
	0x00, 0xff, 0xff, 0xfb, 0x5e, 0xf5, 0x30, 0xea, 0x02, 0x00, 0x00,
}
