load("//bazel:api_build_system.bzl", "udpa_proto_library")

licenses(["notice"])  # Apache 2

udpa_proto_library(
    name = "routing",
    srcs = ["routing.proto"],
    visibility = ["//visibility:public"],
)
