load("//bazel:api_build_system.bzl", "udpa_proto_library")

licenses(["notice"])  # Apache 2

udpa_proto_library(
    name = "orca_load_report",
    srcs = ["orca_load_report.proto"],
    visibility = ["//visibility:public"],
)
