// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/annotations/migrate.proto

package udpa_annotations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MigrateAnnotation struct {
	Rename               string   `protobuf:"bytes,1,opt,name=rename,proto3" json:"rename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateAnnotation) Reset()         { *m = MigrateAnnotation{} }
func (m *MigrateAnnotation) String() string { return proto.CompactTextString(m) }
func (*MigrateAnnotation) ProtoMessage()    {}
func (*MigrateAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba8191732d0e246d, []int{0}
}

func (m *MigrateAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateAnnotation.Unmarshal(m, b)
}
func (m *MigrateAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateAnnotation.Marshal(b, m, deterministic)
}
func (m *MigrateAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateAnnotation.Merge(m, src)
}
func (m *MigrateAnnotation) XXX_Size() int {
	return xxx_messageInfo_MigrateAnnotation.Size(m)
}
func (m *MigrateAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateAnnotation proto.InternalMessageInfo

func (m *MigrateAnnotation) GetRename() string {
	if m != nil {
		return m.Rename
	}
	return ""
}

type FileMigrateAnnotation struct {
	MoveToPackage        string   `protobuf:"bytes,2,opt,name=move_to_package,json=moveToPackage,proto3" json:"move_to_package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMigrateAnnotation) Reset()         { *m = FileMigrateAnnotation{} }
func (m *FileMigrateAnnotation) String() string { return proto.CompactTextString(m) }
func (*FileMigrateAnnotation) ProtoMessage()    {}
func (*FileMigrateAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba8191732d0e246d, []int{1}
}

func (m *FileMigrateAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMigrateAnnotation.Unmarshal(m, b)
}
func (m *FileMigrateAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMigrateAnnotation.Marshal(b, m, deterministic)
}
func (m *FileMigrateAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMigrateAnnotation.Merge(m, src)
}
func (m *FileMigrateAnnotation) XXX_Size() int {
	return xxx_messageInfo_FileMigrateAnnotation.Size(m)
}
func (m *FileMigrateAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMigrateAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_FileMigrateAnnotation proto.InternalMessageInfo

func (m *FileMigrateAnnotation) GetMoveToPackage() string {
	if m != nil {
		return m.MoveToPackage
	}
	return ""
}

var E_MessageMigrate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MigrateAnnotation)(nil),
	Field:         171962766,
	Name:          "udpa.annotations.message_migrate",
	Tag:           "bytes,171962766,opt,name=message_migrate",
	Filename:      "udpa/annotations/migrate.proto",
}

var E_FieldMigrate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MigrateAnnotation)(nil),
	Field:         171962766,
	Name:          "udpa.annotations.field_migrate",
	Tag:           "bytes,171962766,opt,name=field_migrate",
	Filename:      "udpa/annotations/migrate.proto",
}

var E_EnumMigrate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*MigrateAnnotation)(nil),
	Field:         171962766,
	Name:          "udpa.annotations.enum_migrate",
	Tag:           "bytes,171962766,opt,name=enum_migrate",
	Filename:      "udpa/annotations/migrate.proto",
}

var E_EnumValueMigrate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*MigrateAnnotation)(nil),
	Field:         171962766,
	Name:          "udpa.annotations.enum_value_migrate",
	Tag:           "bytes,171962766,opt,name=enum_value_migrate",
	Filename:      "udpa/annotations/migrate.proto",
}

var E_FileMigrate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*FileMigrateAnnotation)(nil),
	Field:         171962766,
	Name:          "udpa.annotations.file_migrate",
	Tag:           "bytes,171962766,opt,name=file_migrate",
	Filename:      "udpa/annotations/migrate.proto",
}

func init() {
	proto.RegisterType((*MigrateAnnotation)(nil), "udpa.annotations.MigrateAnnotation")
	proto.RegisterType((*FileMigrateAnnotation)(nil), "udpa.annotations.FileMigrateAnnotation")
	proto.RegisterExtension(E_MessageMigrate)
	proto.RegisterExtension(E_FieldMigrate)
	proto.RegisterExtension(E_EnumMigrate)
	proto.RegisterExtension(E_EnumValueMigrate)
	proto.RegisterExtension(E_FileMigrate)
}

func init() { proto.RegisterFile("udpa/annotations/migrate.proto", fileDescriptor_ba8191732d0e246d) }

var fileDescriptor_ba8191732d0e246d = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0xe9, 0x7f, 0x51, 0xf8, 0x4f, 0x5b, 0x5b, 0x03, 0x4a, 0x11, 0x3f, 0x62, 0x05, 0x2d,
	0x08, 0x13, 0xd0, 0x5d, 0x37, 0xe2, 0xc2, 0xee, 0x8a, 0x1a, 0xc4, 0x6d, 0x98, 0x36, 0x37, 0xc3,
	0xd8, 0xcc, 0x07, 0xc9, 0xa4, 0xbe, 0x85, 0x2f, 0xe9, 0x83, 0x28, 0x33, 0xf9, 0xa8, 0x38, 0xc5,
	0x45, 0x96, 0xb9, 0x67, 0xce, 0xf9, 0x9d, 0x1b, 0x2e, 0x3a, 0x2d, 0x62, 0x45, 0x02, 0x22, 0x84,
	0xd4, 0x44, 0x33, 0x29, 0xf2, 0x80, 0x33, 0x9a, 0x11, 0x0d, 0x58, 0x65, 0x52, 0x4b, 0x6f, 0x64,
	0x74, 0xfc, 0x43, 0x3f, 0xf2, 0xa9, 0x94, 0x34, 0x85, 0xc0, 0xea, 0xcb, 0x22, 0x09, 0x62, 0xc8,
	0x57, 0x19, 0x53, 0x5a, 0x66, 0xa5, 0x67, 0x72, 0x8d, 0xf6, 0x17, 0x65, 0xc8, 0x7d, 0xe3, 0xf3,
	0x0e, 0x51, 0x37, 0x03, 0x41, 0x38, 0x8c, 0x3b, 0x7e, 0x67, 0xfa, 0x3f, 0xac, 0xbe, 0x26, 0x77,
	0xe8, 0x60, 0xce, 0x52, 0x70, 0x0d, 0x97, 0x68, 0xc8, 0xe5, 0x06, 0x22, 0x2d, 0x23, 0x45, 0x56,
	0x6b, 0x42, 0x61, 0xfc, 0xcf, 0x3a, 0x07, 0x66, 0xfc, 0x22, 0x9f, 0xca, 0xe1, 0x4c, 0xa1, 0x21,
	0x87, 0x3c, 0x27, 0x14, 0xa2, 0xaa, 0xba, 0x77, 0x86, 0xcb, 0x8e, 0xb8, 0xee, 0x88, 0x17, 0xe5,
	0x8b, 0x47, 0x65, 0x77, 0x18, 0x7f, 0x7c, 0x7e, 0x3d, 0xfb, 0x9d, 0x69, 0xef, 0xe6, 0x02, 0xff,
	0xde, 0x0f, 0x3b, 0x4d, 0xc2, 0xbd, 0x2a, 0xbf, 0x52, 0x66, 0x6f, 0x68, 0x90, 0x30, 0x48, 0xe3,
	0x86, 0x77, 0xe2, 0xf0, 0xe6, 0x46, 0x6f, 0x47, 0xeb, 0xdb, 0xec, 0x9a, 0x45, 0x51, 0x1f, 0x44,
	0xc1, 0x1b, 0xd4, 0xb1, 0x83, 0x7a, 0x10, 0x05, 0x6f, 0x47, 0xea, 0x99, 0xe4, 0x1a, 0xf4, 0x8e,
	0x3c, 0x0b, 0xda, 0x90, 0xb4, 0xd8, 0xfe, 0xc9, 0xf3, 0x9d, 0xb8, 0x57, 0xf3, 0xa6, 0x1d, 0x73,
	0x04, 0xb5, 0xbf, 0x06, 0xaf, 0x51, 0x3f, 0x61, 0x29, 0xfc, 0xb1, 0xa1, 0xb9, 0x0f, 0x87, 0x76,
	0xe5, 0xd2, 0x76, 0xde, 0x51, 0xd8, 0x4b, 0xb6, 0xe3, 0x65, 0xd7, 0x86, 0xde, 0x7e, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x5a, 0x28, 0x89, 0xcd, 0xf7, 0x02, 0x00, 0x00,
}
