// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/annotations/protodoc.proto

package udpa_annotations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtodocAnnotation struct {
	NotImplementedHide   bool     `protobuf:"varint,1,opt,name=not_implemented_hide,json=notImplementedHide,proto3" json:"not_implemented_hide,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtodocAnnotation) Reset()         { *m = ProtodocAnnotation{} }
func (m *ProtodocAnnotation) String() string { return proto.CompactTextString(m) }
func (*ProtodocAnnotation) ProtoMessage()    {}
func (*ProtodocAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1277247e057a0829, []int{0}
}

func (m *ProtodocAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtodocAnnotation.Unmarshal(m, b)
}
func (m *ProtodocAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtodocAnnotation.Marshal(b, m, deterministic)
}
func (m *ProtodocAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtodocAnnotation.Merge(m, src)
}
func (m *ProtodocAnnotation) XXX_Size() int {
	return xxx_messageInfo_ProtodocAnnotation.Size(m)
}
func (m *ProtodocAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtodocAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_ProtodocAnnotation proto.InternalMessageInfo

func (m *ProtodocAnnotation) GetNotImplementedHide() bool {
	if m != nil {
		return m.NotImplementedHide
	}
	return false
}

var E_MessageDoc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*ProtodocAnnotation)(nil),
	Field:         81912196,
	Name:          "udpa.annotations.message_doc",
	Tag:           "bytes,81912196,opt,name=message_doc",
	Filename:      "udpa/annotations/protodoc.proto",
}

var E_FieldDoc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*ProtodocAnnotation)(nil),
	Field:         81912196,
	Name:          "udpa.annotations.field_doc",
	Tag:           "bytes,81912196,opt,name=field_doc",
	Filename:      "udpa/annotations/protodoc.proto",
}

var E_EnumDoc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*ProtodocAnnotation)(nil),
	Field:         81912196,
	Name:          "udpa.annotations.enum_doc",
	Tag:           "bytes,81912196,opt,name=enum_doc",
	Filename:      "udpa/annotations/protodoc.proto",
}

var E_EnumValueDoc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*ProtodocAnnotation)(nil),
	Field:         81912196,
	Name:          "udpa.annotations.enum_value_doc",
	Tag:           "bytes,81912196,opt,name=enum_value_doc",
	Filename:      "udpa/annotations/protodoc.proto",
}

var E_ServiceDoc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ProtodocAnnotation)(nil),
	Field:         81912196,
	Name:          "udpa.annotations.service_doc",
	Tag:           "bytes,81912196,opt,name=service_doc",
	Filename:      "udpa/annotations/protodoc.proto",
}

var E_MethodDoc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*ProtodocAnnotation)(nil),
	Field:         81912196,
	Name:          "udpa.annotations.method_doc",
	Tag:           "bytes,81912196,opt,name=method_doc",
	Filename:      "udpa/annotations/protodoc.proto",
}

var E_FileDoc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*ProtodocAnnotation)(nil),
	Field:         81912196,
	Name:          "udpa.annotations.file_doc",
	Tag:           "bytes,81912196,opt,name=file_doc",
	Filename:      "udpa/annotations/protodoc.proto",
}

func init() {
	proto.RegisterType((*ProtodocAnnotation)(nil), "udpa.annotations.ProtodocAnnotation")
	proto.RegisterExtension(E_MessageDoc)
	proto.RegisterExtension(E_FieldDoc)
	proto.RegisterExtension(E_EnumDoc)
	proto.RegisterExtension(E_EnumValueDoc)
	proto.RegisterExtension(E_ServiceDoc)
	proto.RegisterExtension(E_MethodDoc)
	proto.RegisterExtension(E_FileDoc)
}

func init() { proto.RegisterFile("udpa/annotations/protodoc.proto", fileDescriptor_1277247e057a0829) }

var fileDescriptor_1277247e057a0829 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd9, 0xc5, 0x6d, 0x99, 0x88, 0x14, 0x0f, 0x43, 0xd4, 0x4d, 0x11, 0xdc, 0x29, 0x13,
	0xbd, 0xed, 0x26, 0xcc, 0xa1, 0x07, 0x51, 0x26, 0x78, 0x9d, 0x5d, 0xf2, 0xda, 0x05, 0x92, 0xbc,
	0xd0, 0xa6, 0xfb, 0x04, 0x82, 0x1f, 0xcc, 0x2f, 0x26, 0x49, 0x3a, 0x15, 0xbb, 0x5d, 0x72, 0x2b,
	0xfc, 0xdf, 0xfb, 0xfd, 0x5e, 0xfb, 0x2f, 0x19, 0x54, 0xdc, 0xa4, 0xe3, 0x54, 0x6b, 0xb4, 0xa9,
	0x15, 0xa8, 0xcb, 0xb1, 0x29, 0xd0, 0x22, 0x47, 0x46, 0xfd, 0x43, 0x72, 0xe8, 0x06, 0xe8, 0x9f,
	0x81, 0xe3, 0x61, 0x8e, 0x98, 0x4b, 0x08, 0x83, 0xcb, 0x2a, 0x1b, 0x73, 0x28, 0x59, 0x21, 0x8c,
	0xc5, 0x22, 0xec, 0x5c, 0xcc, 0x48, 0xf2, 0x52, 0x53, 0xee, 0x7e, 0x16, 0x93, 0x6b, 0x72, 0xa4,
	0xd1, 0x2e, 0x84, 0x32, 0x12, 0x14, 0x68, 0x0b, 0x7c, 0xb1, 0x12, 0x1c, 0xfa, 0xad, 0x61, 0x6b,
	0xd4, 0x99, 0x27, 0x1a, 0xed, 0xe3, 0x6f, 0xf4, 0x20, 0x38, 0x4c, 0x04, 0xe9, 0x29, 0x28, 0xcb,
	0x34, 0x87, 0x05, 0x47, 0x96, 0x0c, 0x68, 0x30, 0xd3, 0x8d, 0x99, 0x3e, 0x85, 0xf4, 0xd9, 0xf8,
	0xcb, 0xfa, 0x1f, 0x5f, 0x9f, 0x57, 0xc3, 0xd6, 0xa8, 0x77, 0x73, 0x49, 0xff, 0x5f, 0x4d, 0x9b,
	0x07, 0xcd, 0x49, 0x0d, 0x9f, 0x22, 0x9b, 0x30, 0xd2, 0xcd, 0x04, 0x48, 0xee, 0x45, 0xa7, 0x0d,
	0xd1, 0xcc, 0x65, 0x91, 0x9a, 0x8e, 0x07, 0x3b, 0xc9, 0x3b, 0xe9, 0x80, 0xae, 0x94, 0x77, 0x9c,
	0x34, 0x1c, 0xf7, 0xba, 0x52, 0x91, 0x8a, 0xb6, 0xc3, 0x3a, 0x83, 0x21, 0x07, 0xde, 0xb0, 0x4e,
	0x65, 0x15, 0x3e, 0xda, 0xf9, 0x56, 0xcf, 0x9b, 0xcb, 0x23, 0x65, 0xfb, 0xb0, 0x01, 0x38, 0xa3,
	0x20, 0xbd, 0x12, 0x8a, 0xb5, 0x60, 0xbb, 0x3a, 0x7a, 0x0d, 0x69, 0x6c, 0x47, 0x35, 0xdc, 0xa9,
	0x32, 0x42, 0x14, 0xd8, 0x15, 0x86, 0x92, 0xce, 0xb6, 0xfc, 0x0d, 0x2e, 0x8c, 0x14, 0x75, 0x03,
	0xba, 0xae, 0x29, 0x13, 0x12, 0x76, 0xd4, 0x34, 0x13, 0x32, 0xf6, 0x65, 0xda, 0x0e, 0x3b, 0x45,
	0xb6, 0xdc, 0xf3, 0xb4, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xeb, 0x5b, 0x9e, 0x7e,
	0x03, 0x00, 0x00,
}
