// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/annotations/security.proto

package udpa_annotations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldSecurityAnnotation struct {
	SetForUntrustedDownstream bool     `protobuf:"varint,1,opt,name=set_for_untrusted_downstream,json=setForUntrustedDownstream,proto3" json:"set_for_untrusted_downstream,omitempty"`
	SetForUntrustedUpstream   bool     `protobuf:"varint,2,opt,name=set_for_untrusted_upstream,json=setForUntrustedUpstream,proto3" json:"set_for_untrusted_upstream,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *FieldSecurityAnnotation) Reset()         { *m = FieldSecurityAnnotation{} }
func (m *FieldSecurityAnnotation) String() string { return proto.CompactTextString(m) }
func (*FieldSecurityAnnotation) ProtoMessage()    {}
func (*FieldSecurityAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_43b150013eccfb0a, []int{0}
}

func (m *FieldSecurityAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldSecurityAnnotation.Unmarshal(m, b)
}
func (m *FieldSecurityAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldSecurityAnnotation.Marshal(b, m, deterministic)
}
func (m *FieldSecurityAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldSecurityAnnotation.Merge(m, src)
}
func (m *FieldSecurityAnnotation) XXX_Size() int {
	return xxx_messageInfo_FieldSecurityAnnotation.Size(m)
}
func (m *FieldSecurityAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldSecurityAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_FieldSecurityAnnotation proto.InternalMessageInfo

func (m *FieldSecurityAnnotation) GetSetForUntrustedDownstream() bool {
	if m != nil {
		return m.SetForUntrustedDownstream
	}
	return false
}

func (m *FieldSecurityAnnotation) GetSetForUntrustedUpstream() bool {
	if m != nil {
		return m.SetForUntrustedUpstream
	}
	return false
}

var E_Security = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldSecurityAnnotation)(nil),
	Field:         11122993,
	Name:          "udpa.annotations.security",
	Tag:           "bytes,11122993,opt,name=security",
	Filename:      "udpa/annotations/security.proto",
}

func init() {
	proto.RegisterType((*FieldSecurityAnnotation)(nil), "udpa.annotations.FieldSecurityAnnotation")
	proto.RegisterExtension(E_Security)
}

func init() { proto.RegisterFile("udpa/annotations/security.proto", fileDescriptor_43b150013eccfb0a) }

var fileDescriptor_43b150013eccfb0a = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x4d, 0x29, 0x48,
	0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2f, 0x4e, 0x4d,
	0x2e, 0x2d, 0xca, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x00, 0x29, 0xd0,
	0x43, 0x52, 0x20, 0xa5, 0x90, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x0f, 0x96, 0x4f, 0x2a, 0x4d,
	0xd3, 0x4f, 0x49, 0x2d, 0x4e, 0x2e, 0xca, 0x2c, 0x28, 0xc9, 0x2f, 0x82, 0xe8, 0x51, 0x9a, 0xce,
	0xc8, 0x25, 0xee, 0x96, 0x99, 0x9a, 0x93, 0x12, 0x0c, 0x35, 0xcb, 0x11, 0xae, 0x5d, 0xc8, 0x9e,
	0x4b, 0xa6, 0x38, 0xb5, 0x24, 0x3e, 0x2d, 0xbf, 0x28, 0xbe, 0x34, 0xaf, 0xa4, 0xa8, 0xb4, 0xb8,
	0x24, 0x35, 0x25, 0x3e, 0x25, 0xbf, 0x3c, 0xaf, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0x57, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x23, 0x48, 0xb2, 0x38, 0xb5, 0xc4, 0x2d, 0xbf, 0x28, 0x14, 0xa6, 0xc2, 0x05,
	0xae, 0x40, 0xc8, 0x9a, 0x4b, 0x0a, 0xd3, 0x80, 0xd2, 0x02, 0xa8, 0x76, 0x26, 0xb0, 0x76, 0x71,
	0x34, 0xed, 0xa1, 0x50, 0x69, 0xab, 0x74, 0x2e, 0x0e, 0x98, 0xff, 0x84, 0x64, 0xf5, 0x20, 0x1e,
	0xd1, 0x83, 0x79, 0x44, 0x0f, 0xec, 0x66, 0xff, 0x02, 0xb0, 0x37, 0x25, 0x36, 0x7e, 0x5a, 0xc6,
	0xaa, 0xc0, 0xa8, 0xc1, 0x6d, 0xa4, 0xa9, 0x87, 0x1e, 0x04, 0x7a, 0x38, 0x3c, 0x17, 0x04, 0x37,
	0x3c, 0x89, 0x0d, 0x6c, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xc9, 0x02, 0xd5, 0x60,
	0x01, 0x00, 0x00,
}
