// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: udpa/annotations/security.proto

package udpa_annotations

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _security_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ExampleConfig with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ExampleConfig) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Example

	return nil
}

// ExampleConfigValidationError is the validation error returned by
// ExampleConfig.Validate if the designated constraints aren't met.
type ExampleConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExampleConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExampleConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExampleConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExampleConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExampleConfigValidationError) ErrorName() string { return "ExampleConfigValidationError" }

// Error satisfies the builtin error interface
func (e ExampleConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExampleConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExampleConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExampleConfigValidationError{}

// Validate checks the field values on FieldSecurityAnnotation with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *FieldSecurityAnnotation) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ConfigureForUntrustedDownstream

	// no validation rules for ConfigureForUntrustedUpstream

	for idx, item := range m.GetExampleConfigs() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FieldSecurityAnnotationValidationError{
					field:  fmt.Sprintf("ExampleConfigs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// FieldSecurityAnnotationValidationError is the validation error returned by
// FieldSecurityAnnotation.Validate if the designated constraints aren't met.
type FieldSecurityAnnotationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FieldSecurityAnnotationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FieldSecurityAnnotationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FieldSecurityAnnotationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FieldSecurityAnnotationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FieldSecurityAnnotationValidationError) ErrorName() string {
	return "FieldSecurityAnnotationValidationError"
}

// Error satisfies the builtin error interface
func (e FieldSecurityAnnotationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFieldSecurityAnnotation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FieldSecurityAnnotationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FieldSecurityAnnotationValidationError{}
