// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/annotations/security.proto

package udpa_annotations

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExampleConfig struct {
	Example              string   `protobuf:"bytes,1,opt,name=example,proto3" json:"example,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleConfig) Reset()         { *m = ExampleConfig{} }
func (m *ExampleConfig) String() string { return proto.CompactTextString(m) }
func (*ExampleConfig) ProtoMessage()    {}
func (*ExampleConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_43b150013eccfb0a, []int{0}
}

func (m *ExampleConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleConfig.Unmarshal(m, b)
}
func (m *ExampleConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleConfig.Marshal(b, m, deterministic)
}
func (m *ExampleConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleConfig.Merge(m, src)
}
func (m *ExampleConfig) XXX_Size() int {
	return xxx_messageInfo_ExampleConfig.Size(m)
}
func (m *ExampleConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleConfig proto.InternalMessageInfo

func (m *ExampleConfig) GetExample() string {
	if m != nil {
		return m.Example
	}
	return ""
}

type FieldSecurityAnnotation struct {
	ConfigureForUntrustedDownstream bool             `protobuf:"varint,1,opt,name=configure_for_untrusted_downstream,json=configureForUntrustedDownstream,proto3" json:"configure_for_untrusted_downstream,omitempty"`
	ConfigureForUntrustedUpstream   bool             `protobuf:"varint,2,opt,name=configure_for_untrusted_upstream,json=configureForUntrustedUpstream,proto3" json:"configure_for_untrusted_upstream,omitempty"`
	ExampleConfigs                  []*ExampleConfig `protobuf:"bytes,3,rep,name=example_configs,json=exampleConfigs,proto3" json:"example_configs,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}         `json:"-"`
	XXX_unrecognized                []byte           `json:"-"`
	XXX_sizecache                   int32            `json:"-"`
}

func (m *FieldSecurityAnnotation) Reset()         { *m = FieldSecurityAnnotation{} }
func (m *FieldSecurityAnnotation) String() string { return proto.CompactTextString(m) }
func (*FieldSecurityAnnotation) ProtoMessage()    {}
func (*FieldSecurityAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_43b150013eccfb0a, []int{1}
}

func (m *FieldSecurityAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldSecurityAnnotation.Unmarshal(m, b)
}
func (m *FieldSecurityAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldSecurityAnnotation.Marshal(b, m, deterministic)
}
func (m *FieldSecurityAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldSecurityAnnotation.Merge(m, src)
}
func (m *FieldSecurityAnnotation) XXX_Size() int {
	return xxx_messageInfo_FieldSecurityAnnotation.Size(m)
}
func (m *FieldSecurityAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldSecurityAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_FieldSecurityAnnotation proto.InternalMessageInfo

func (m *FieldSecurityAnnotation) GetConfigureForUntrustedDownstream() bool {
	if m != nil {
		return m.ConfigureForUntrustedDownstream
	}
	return false
}

func (m *FieldSecurityAnnotation) GetConfigureForUntrustedUpstream() bool {
	if m != nil {
		return m.ConfigureForUntrustedUpstream
	}
	return false
}

func (m *FieldSecurityAnnotation) GetExampleConfigs() []*ExampleConfig {
	if m != nil {
		return m.ExampleConfigs
	}
	return nil
}

var E_Security = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldSecurityAnnotation)(nil),
	Field:         11122993,
	Name:          "udpa.annotations.security",
	Tag:           "bytes,11122993,opt,name=security",
	Filename:      "udpa/annotations/security.proto",
}

func init() {
	proto.RegisterType((*ExampleConfig)(nil), "udpa.annotations.ExampleConfig")
	proto.RegisterType((*FieldSecurityAnnotation)(nil), "udpa.annotations.FieldSecurityAnnotation")
	proto.RegisterExtension(E_Security)
}

func init() { proto.RegisterFile("udpa/annotations/security.proto", fileDescriptor_43b150013eccfb0a) }

var fileDescriptor_43b150013eccfb0a = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x95, 0x56, 0x94, 0xe0, 0x8a, 0x8b, 0xbc, 0x34, 0x54, 0xaa, 0x1a, 0x75, 0x6a, 0x17,
	0x47, 0x2a, 0x1b, 0x1b, 0xb7, 0x82, 0xc4, 0x80, 0x14, 0xd4, 0x39, 0x72, 0x6b, 0x37, 0xb2, 0x94,
	0xda, 0x96, 0x2f, 0x5c, 0x36, 0x9e, 0x86, 0x9d, 0x95, 0x27, 0x60, 0xe5, 0x55, 0xd8, 0xd8, 0x10,
	0x8e, 0x13, 0x95, 0x96, 0x6e, 0x39, 0x39, 0xdf, 0xf9, 0x7c, 0xfc, 0x1b, 0xf4, 0x2d, 0x91, 0x38,
	0xc1, 0x9c, 0x0b, 0x83, 0x0d, 0x13, 0x5c, 0x27, 0x9a, 0xce, 0xad, 0x62, 0xe6, 0x19, 0x49, 0x25,
	0x8c, 0x80, 0x47, 0xbf, 0x00, 0x5a, 0x01, 0xba, 0xbd, 0xcd, 0x11, 0x83, 0x8d, 0xd5, 0xe5, 0x40,
	0xf7, 0x38, 0x17, 0x22, 0x2f, 0x68, 0xe2, 0xaa, 0x99, 0x5d, 0x24, 0x98, 0x7b, 0x57, 0x37, 0x5e,
	0x6f, 0x11, 0xaa, 0xe7, 0x8a, 0x49, 0x23, 0x94, 0x27, 0x3a, 0x0f, 0xb8, 0x60, 0x04, 0x1b, 0x9a,
	0x54, 0x1f, 0x65, 0x63, 0x30, 0x02, 0xfb, 0x57, 0x4f, 0x78, 0x29, 0x0b, 0x7a, 0x21, 0xf8, 0x82,
	0xe5, 0x30, 0x02, 0xbb, 0xb4, 0xfc, 0x11, 0x05, 0x71, 0x30, 0xdc, 0x4b, 0xab, 0x72, 0xf0, 0x1d,
	0x80, 0xce, 0x84, 0xd1, 0x82, 0xdc, 0xfb, 0x9b, 0x9c, 0xd5, 0xab, 0xc2, 0x5b, 0x30, 0x98, 0xbb,
	0x79, 0xab, 0x68, 0xb6, 0x10, 0x2a, 0xb3, 0xdc, 0x28, 0xab, 0x0d, 0x25, 0x19, 0x11, 0x8f, 0x5c,
	0x1b, 0x45, 0xf1, 0xd2, 0x09, 0xc3, 0xb4, 0x5f, 0x93, 0x13, 0xa1, 0xa6, 0x15, 0x77, 0x59, 0x63,
	0xf0, 0x1a, 0xc4, 0xdb, 0x64, 0x56, 0x7a, 0x55, 0xc3, 0xa9, 0x7a, 0xff, 0xaa, 0xa6, 0x1e, 0x82,
	0x37, 0xe0, 0xd0, 0x2f, 0x9f, 0x95, 0xa0, 0x8e, 0x9a, 0x71, 0x73, 0xd8, 0x1e, 0xf7, 0xd1, 0x7a,
	0xfa, 0xe8, 0x4f, 0x0a, 0xe9, 0x01, 0x5d, 0x2d, 0xf5, 0x69, 0x0e, 0xc2, 0xea, 0xfd, 0x60, 0x0f,
	0x95, 0x71, 0xa3, 0x2a, 0x6e, 0xe4, 0x52, 0xb9, 0x93, 0x4e, 0x14, 0xbd, 0x7d, 0xbd, 0xee, 0xc4,
	0xc1, 0xb0, 0x3d, 0x1e, 0x6d, 0x1e, 0xb2, 0x25, 0xbe, 0xb4, 0x96, 0x9f, 0x87, 0xef, 0x2f, 0x1f,
	0x9f, 0xad, 0x46, 0x18, 0xcc, 0x5a, 0x4e, 0x7f, 0xf2, 0x13, 0x00, 0x00, 0xff, 0xff, 0x16, 0x01,
	0x74, 0xa8, 0x4a, 0x02, 0x00, 0x00,
}
