// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/annotations/status.proto

package udpa_annotations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusAnnotation struct {
	Wip                  bool     `protobuf:"varint,1,opt,name=wip,proto3" json:"wip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusAnnotation) Reset()         { *m = StatusAnnotation{} }
func (m *StatusAnnotation) String() string { return proto.CompactTextString(m) }
func (*StatusAnnotation) ProtoMessage()    {}
func (*StatusAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_011cc2e7e491b0ff, []int{0}
}

func (m *StatusAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusAnnotation.Unmarshal(m, b)
}
func (m *StatusAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusAnnotation.Marshal(b, m, deterministic)
}
func (m *StatusAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusAnnotation.Merge(m, src)
}
func (m *StatusAnnotation) XXX_Size() int {
	return xxx_messageInfo_StatusAnnotation.Size(m)
}
func (m *StatusAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_StatusAnnotation proto.InternalMessageInfo

func (m *StatusAnnotation) GetWip() bool {
	if m != nil {
		return m.Wip
	}
	return false
}

var E_MessageStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*StatusAnnotation)(nil),
	Field:         222707719,
	Name:          "udpa.annotations.message_status",
	Tag:           "bytes,222707719,opt,name=message_status",
	Filename:      "udpa/annotations/status.proto",
}

var E_FieldStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*StatusAnnotation)(nil),
	Field:         222707719,
	Name:          "udpa.annotations.field_status",
	Tag:           "bytes,222707719,opt,name=field_status",
	Filename:      "udpa/annotations/status.proto",
}

var E_EnumStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*StatusAnnotation)(nil),
	Field:         222707719,
	Name:          "udpa.annotations.enum_status",
	Tag:           "bytes,222707719,opt,name=enum_status",
	Filename:      "udpa/annotations/status.proto",
}

var E_EnumValueStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*StatusAnnotation)(nil),
	Field:         222707719,
	Name:          "udpa.annotations.enum_value_status",
	Tag:           "bytes,222707719,opt,name=enum_value_status",
	Filename:      "udpa/annotations/status.proto",
}

var E_FileStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*StatusAnnotation)(nil),
	Field:         222707719,
	Name:          "udpa.annotations.file_status",
	Tag:           "bytes,222707719,opt,name=file_status",
	Filename:      "udpa/annotations/status.proto",
}

func init() {
	proto.RegisterType((*StatusAnnotation)(nil), "udpa.annotations.StatusAnnotation")
	proto.RegisterExtension(E_MessageStatus)
	proto.RegisterExtension(E_FieldStatus)
	proto.RegisterExtension(E_EnumStatus)
	proto.RegisterExtension(E_EnumValueStatus)
	proto.RegisterExtension(E_FileStatus)
}

func init() { proto.RegisterFile("udpa/annotations/status.proto", fileDescriptor_011cc2e7e491b0ff) }

var fileDescriptor_011cc2e7e491b0ff = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd0, 0xbf, 0x4b, 0xc4, 0x30,
	0x14, 0x07, 0x70, 0x8a, 0x20, 0xf2, 0xea, 0x8f, 0xda, 0xe9, 0x10, 0x0f, 0xeb, 0xe1, 0x70, 0x53,
	0x0a, 0xba, 0xdd, 0xe6, 0xe0, 0x6d, 0x22, 0x9c, 0xe0, 0x2a, 0x39, 0xfb, 0x5a, 0x22, 0x69, 0x12,
	0x9a, 0x44, 0x57, 0x37, 0xff, 0x06, 0xff, 0x5b, 0x49, 0xd2, 0x9c, 0x72, 0xa7, 0x4b, 0xb6, 0xd2,
	0xef, 0x7b, 0xdf, 0x4f, 0x5f, 0x61, 0x6a, 0x1b, 0x45, 0x6b, 0x2a, 0x84, 0x34, 0xd4, 0x30, 0x29,
	0x74, 0xad, 0x0d, 0x35, 0x56, 0x13, 0x35, 0x48, 0x23, 0xcb, 0xc2, 0xc5, 0xe4, 0x57, 0x7c, 0x56,
	0x75, 0x52, 0x76, 0x1c, 0x6b, 0x9f, 0xaf, 0x6d, 0x5b, 0x37, 0xa8, 0x5f, 0x06, 0xa6, 0x8c, 0x1c,
	0xc2, 0xce, 0xec, 0x0a, 0x8a, 0x47, 0xdf, 0x71, 0xbb, 0x59, 0x2b, 0x0b, 0xd8, 0x7b, 0x67, 0x6a,
	0x92, 0x55, 0xd9, 0xfc, 0x60, 0xe5, 0x1e, 0x17, 0x3d, 0x1c, 0xf7, 0xa8, 0x35, 0xed, 0xf0, 0x39,
	0x88, 0xe5, 0x05, 0x09, 0xd5, 0x24, 0x56, 0x93, 0xfb, 0x30, 0xf0, 0xa0, 0x3c, 0x3d, 0xf9, 0xfc,
	0xf8, 0x7a, 0xad, 0xb2, 0x79, 0x7e, 0x3d, 0x23, 0xdb, 0x9f, 0x45, 0xb6, 0xc5, 0xd5, 0xd1, 0xd8,
	0x1e, 0x82, 0x45, 0x07, 0x87, 0x2d, 0x43, 0xde, 0x44, 0x6c, 0xba, 0x83, 0x2d, 0x5d, 0x9c, 0x44,
	0xe5, 0xbe, 0x79, 0x84, 0x1a, 0xc8, 0x51, 0xd8, 0x3e, 0x3a, 0xe7, 0x3b, 0xce, 0x9d, 0xb0, 0x7d,
	0x12, 0x03, 0xae, 0x77, 0x54, 0x0c, 0x9c, 0x7a, 0xe5, 0x8d, 0x72, 0xbb, 0xf9, 0x81, 0x97, 0x7f,
	0x5a, 0x4f, 0x6e, 0x24, 0x09, 0x3c, 0xc1, 0xb8, 0xfe, 0x73, 0x5b, 0xcb, 0x38, 0xfe, 0x7f, 0xdb,
	0x92, 0xf1, 0x34, 0x0a, 0x5c, 0x6f, 0x78, 0xbb, 0xde, 0xf7, 0x75, 0x37, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf5, 0x90, 0x57, 0xab, 0x9b, 0x02, 0x00, 0x00,
}
