trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - 'v*'

jobs:
- job: CI
  container: envoyproxy/envoy-build-ubuntu@sha256:f0b2453c3587e3297f5caf5e97fbf57c97592c96136209ec13fe2795aae2c896
  steps:
  - task: CacheBeta@1
    key: './WORKSPACE | **/*.bzl'
    path: /tmp/repository_cache

  - bash: bazel test --config=ci //...
